export const cars = [
    {
      id: 1,
      name: 'Toyota Camry',
      img: 'https://static.pakwheels.com/2023/11/rt.jpg',
      model: '2023',
      price: 30000,
      no: 'XYZ 123',
      registeredIn: 'New York',
      color: 'Silver',
      assembly: 'Japan',
      engineCapacity: '2.5L',
      bodyType: 'Sedan',
      carType: 'New',
      additionalDetails: 'Automatic transmission, leather seats',
      createdAt: '2023-01-01',
      updatedAt: '2023-01-01',
    },
    {
      id: 2,
      name: 'Honda Accord',
      img: 'https://upload.wikimedia.org/wikipedia/commons/2/26/2023_Honda_Accord_LX%2C_front_left%2C_07-13-2023.jpg',
      model: '2022',
      price: 28000,
      no: 'ABC 456',
      registeredIn: 'California',
      color: 'Blue',
      assembly: 'USA',
      engineCapacity: '2.0L',
      bodyType: 'Sedan',
      carType: 'New',
      additionalDetails: 'Sunroof, advanced safety features',
      createdAt: '2022-12-15',
      updatedAt: '2022-12-15',
    },
    {
      id: 3,
      name: 'Ford Mustang',
      img: 'https://www.motortrend.com/uploads/2023/08/008-2024-Ford-Mustang-GT-Premium-Performance-pack-front-three-quarters.jpg?fit=around%7C875:492',
      model: '2022',
      price: 45000,
      no: 'LMN 789',
      registeredIn: 'Texas',
      color: 'Red',
      assembly: 'USA',
      engineCapacity: '5.0L',
      bodyType: 'Coupe',
      carType: 'New',
      additionalDetails: 'Manual transmission, sports package',
      createdAt: '2022-12-10',
      updatedAt: '2022-12-10',
    },
    {
      id: 4,
      name: 'Chevrolet Tahoe',
      img: 'https://hips.hearstapps.com/hmg-prod/images/2025-chevrolet-tahoe-102-65650874ea106.jpg?crop=0.710xw:0.601xh;0.179xw,0.197xh&resize=1200:*',
      model: '2022',
      price: 55000,
      no: 'PQR 987',
      registeredIn: 'Florida',
      color: 'Black',
      assembly: 'USA',
      engineCapacity: '6.2L',
      bodyType: 'SUV',
      carType: 'New',
      additionalDetails: 'Third-row seating, towing package',
      createdAt: '2022-12-05',
      updatedAt: '2022-12-05',
    },
    {
      id: 5,
      name: 'Volkswagen Golf',
      img: 'https://cdn.motor1.com/images/mgl/3KVg1/s1/2022-volkswagen-golf-r-exterior.webp',
      model: '2023',
      price: 23000,
      no: 'JKL 321',
      registeredIn: 'Illinois',
      color: 'White',
      assembly: 'Germany',
      engineCapacity: '1.8L',
      bodyType: 'Hatchback',
      carType: 'New',
      additionalDetails: 'Fuel-efficient, compact design',
      createdAt: '2023-01-05',
      updatedAt: '2023-01-05',
    },
  ];
  